apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
  name: mysql-service
spec: 
  ports: 
    -
      port: 3306
  selector: 
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
        - 
          image: mysql_service
          name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
      volumes:
            - name: mysql
              persistentVolumeClaim:
                claimName: mysql-pvc
